# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: klint-format
        name: klint code formatted
        description: Use klint to format your kotlin code.
        language: script
        types: [kotlin]
        always_run: true
        pass_filenames: false
        entry: ./.hooks/klint-format.sh
